global:
  resolve_timeout: 5m

route:
  receiver: "autoscale-webhook"

receivers:
  - name: "autoscale-webhook"
    webhook_configs:
      - url: "http://localhost:5001/autoscale"
        send_resolved: true